name: PR-build

on: 
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: tests
    runs-on: ubuntu-18.04
    env:
      CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
